spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zmall-goods?useUnicode=true&useSSL=true
    username: root
    password: 111111
mapper:
  mappers:
    - com.fanyetu.common.mapper.CommonMapper
  identity: mysql
pagehelper:
  helper-dialect: mysql
  reasonable: true
mybatis:
  type-aliases-package: com.fanyetu.zmallgoods.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
